# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build package with Maven
      run: mvn -B package --file reversi-game/pom.xml
    - name: Make output directory and copy jar file
      run: mkdir out && cp reversi-game/target/*-jar-with-dependencies.jar out
    - uses: actions/upload-artifact@v1
      with:
        name: Reversi
        path: out
    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ steps.tag.outputs.result }}
        draft: false
        prerelease: false
